{{- if eq .Values.role "service" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pod.name }}
spec:
  selector:
    user: {{ .Values.labels.user }}
    app: pros_app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
{{- end }}