{{- if eq .Values.role "slam-unity" }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
  labels:
    user: {{ .Values.labels.user }}
    app: pros_app
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-work1
  containers:
    - name: rplidar
      image: "{{ .Values.image.registry }}/screamlab/pros_jetson_driver_image:0.1.0"
      envFrom:
        - configMapRef:
            name: slam-unity-env-config
      volumeMounts:
        - name: demo-volume
          mountPath: /workspace/demo
      command: ["/bin/bash", "-c"]
      args:
        - |
          source /opt/ros/humble/setup.bash && \
          source /workspaces/install/setup.bash && \
          ros2 launch /workspace/demo/rplidar_unity.xml

    # -------------------- lidar-transform service --------------------
    - name: lidar-transform
      image: "{{ .Values.image.registry }}/screamlab/pros_unity_lidar_trans_image:latest"
      envFrom:
        - configMapRef:
            name: slam-unity-env-config
      command: ["/bin/bash", "-c"]
      args:
        - |
          source /opt/ros/humble/setup.bash && \
          source /workspaces/install/setup.bash && \
          ros2 run unity_lidar_transformer lidar_transformer_node

    # # -------------------- slam service --------------------
    - name: slam
      image: "{{ .Values.image.registry }}/screamlab/pros_jetson_driver_image:0.1.0"
      envFrom:
        - configMapRef:
            name: slam-unity-env-config
      volumeMounts:
        - name: demo-volume
          mountPath: /workspace/demo
      command: ["/bin/bash", "-c"]
      args:
        - |
          source /opt/ros/humble/setup.bash && \
          source /workspaces/install/setup.bash && \
          ros2 launch /workspace/demo/slam.xml

    # -------------------- rosbridge service --------------------
    - name: rosbridge
      image: "{{ .Values.image.registry }}/screamlab/pros_jetson_driver_image:0.1.0"
      envFrom:
        - configMapRef:
            name: slam-unity-env-config
      ports:
        - containerPort: 9090
      command: ["/bin/bash", "-c"]
      args:
        - |
          source /opt/ros/humble/setup.bash && \
          source /workspaces/install/setup.bash && \
          ros2 launch rosbridge_server rosbridge_websocket_launch.xml
    # -------------------- car control service --------------------   
    - name: pros-car
      image: "{{ .Values.image.registry }}/screamlab/pros_car_docker_image:latest"
      command: ["/bin/bash", "-c", "--"]
      args: ["trap : TERM INT; sleep infinity & wait"]
      envFrom:
        - configMapRef:
            name: slam-unity-env-config
      volumeMounts:
        - name: src-volume
          mountPath: /workspaces/src
        - name: screenshots-volume
          mountPath: /workspaces/screenshots

      resources:
        requests:
          memory: "256Mi"
        limits:
          nvidia.com/gpu.shared: 1
    # -------------------- yolo service -------------------- 
    - name: pros-cameraapi
      image: master.harbor.registry/screamlab/screamlab/pros_cameraapi:0.0.2
      command: ["/bin/bash", "-c", "--"]
      args: ["trap : TERM INT; sleep infinity & wait"]
      envFrom:
        - configMapRef:
            name: slam-unity-env-config
      volumeMounts:
        - name: yolo-src-volume
          mountPath: /workspaces/src
        - name: yolo-screenshots-volume
          mountPath: /workspaces/screenshots
        - name: yolo-fps-screenshots-volume
          mountPath: /workspaces/fps_screenshots
      resources:
        requests:
          memory: "256Mi"
        limits:
          nvidia.com/gpu.shared: 1
  # -------------------- Shared volume definition --------------------
  volumes:
    - name: demo-volume
      hostPath:
        path: "{{ .Values.workspace.path }}/pros_app/docker/compose/demo" # Replace with actual host path
        type: Directory
    - name: src-volume
      hostPath:
        path: "{{ .Values.workspace.path }}/pros_car/src"
        type: Directory
    - name: screenshots-volume
      hostPath:
        path: "{{ .Values.workspace.path }}/pros_car/screenshots"
        type: Directory
    - name: yolo-src-volume
      hostPath:
        path: "{{ .Values.workspace.path }}/ros2_yolo_integration/src"
        type: Directory
    - name: yolo-screenshots-volume
      hostPath:
        path: "{{ .Values.workspace.path }}/ros2_yolo_integration/screenshots"
        type: Directory
    - name: yolo-fps-screenshots-volume
      hostPath:
        path: "{{ .Values.workspace.path }}/ros2_yolo_integration/fps_screenshots"
        type: Directory
---
# Environment variable configuration (must create ConfigMap first)
apiVersion: v1
kind: ConfigMap
metadata:
  name: slam-unity-env-config
data:
  ROS_DOMAIN_ID: "{{ .Values.domain.id }}"
  WHEEL_SPEED: "10"
{{- end }}